import { writeFileSync } from 'fs';
import { join } from 'path';

export const BRIDGE_OVERLAY_FILENAME = 'bridge.override.yml';

const OVERLAY_CONTENT =
  '# Auto-generated by the-bridge. Do not edit.\n' +
  'networks:\n' +
  '  default:\n' +
  '    name: homelab_stack\n' +
  '    external: true\n';

export function writeBridgeOverlay(workDir: string): string {
  const overlayPath = join(workDir, BRIDGE_OVERLAY_FILENAME);
  writeFileSync(overlayPath, OVERLAY_CONTENT, 'utf-8');
  return overlayPath;
}
